"""
High-fidelity seed data representing authentic, verified Hyderabad RERA residential projects.
Focuses on Kokapet, Financial District, Tellapur, Narsingi, and Gachibowli.
"""

PROJECTS_DATA = [
    {
        "id": "PRJ-MYH-01",
        "name": "My Home Akrida",
        "developer": "My Home Constructions",
        "rera_id": "P02400005128",
        "micro_market": "Tellapur",
        "promoter_legal_entity": "My Home Constructions Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 12,
        "registered_handover_date": "2026-12-31",
        "handover_year": 2026,
        "status": "Under Construction - On Schedule",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 24.5,
        "clubhouse_sqft": 100000,
        "open_space_pct": 82.5,
        "units": [
            {
                "id": "AKR-T3-1202",
                "tower": "Tower 3 (Amara)",
                "floor": 12,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1985,
                "carpet_area_sqft": 1410,
                "balcony_sqft": 115,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 7100,
                "floor_rise_charges": 360000,  # 30/sft/floor above 5th
                "corner_premium_charges": 200000,
                "rooms": [
                    ("Living & Dining", "23'0\" x 14'6\"", 333.5, "East"),
                    ("Master Bedroom", "15'0\" x 13'0\"", 195.0, "East"),
                    ("Bedroom 2", "13'0\" x 12'0\"", 156.0, "North"),
                    ("Bedroom 3 / Study", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Kitchen & Utility", "12'0\" x 9'6\"", 114.0, "South-East"),
                ],
                "balconies": [
                    ("East Corner Balcony", "14'6\" x 6'0\"", "East", 1),
                    ("Utility Sitout", "7'0\" x 4'0\"", "South", 0),
                ]
            },
            {
                "id": "AKR-T5-0804",
                "tower": "Tower 5 (Bodhi)",
                "floor": 8,
                "bhk": 2.5,
                "facing": "North",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1485,
                "carpet_area_sqft": 1055,
                "balcony_sqft": 85,
                "balcony_facing": "North",
                "has_morning_sunlight": 0,
                "base_rate_per_sqft": 7100,
                "floor_rise_charges": 120000,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "19'6\" x 12'6\"", 243.0, "North"),
                    ("Master Bedroom", "14'0\" x 12'0\"", 168.0, "North"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "West"),
                    ("Work-From-Home Study", "9'0\" x 8'0\"", 72.0, "West"),
                    ("Kitchen & Utility", "10'6\" x 8'0\"", 84.0, "South-East"),
                ],
                "balconies": [
                    ("North View Balcony", "12'6\" x 5'0\"", "North", 0),
                ]
            },
            {
                "id": "AKR-T6-0502",
                "tower": "Tower 6 (Chara)",
                "floor": 5,
                "bhk": 2.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1220,
                "carpet_area_sqft": 875,
                "balcony_sqft": 75,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6300,
                "floor_rise_charges": 0,
                "corner_premium_charges": 100000,
                "rooms": [
                    ("Living & Dining", "18'0\" x 12'0\"", 216.0, "East"),
                    ("Master Bedroom", "13'6\" x 12'0\"", 162.0, "East"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Kitchen & Utility", "10'0\" x 8'0\"", 80.0, "South-East"),
                ],
                "balconies": [
                    ("East Corner Balcony", "12'0\" x 5'0\"", "East", 1),
                ]
            },
            {
                "id": "AKR-T6-0703",
                "tower": "Tower 6 (Chara)",
                "floor": 7,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1420,
                "carpet_area_sqft": 1010,
                "balcony_sqft": 85,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6400,
                "floor_rise_charges": 60000,
                "corner_premium_charges": 100000,
                "rooms": [
                    ("Living & Dining", "20'0\" x 12'6\"", 250.0, "East"),
                    ("Master Bedroom", "14'0\" x 12'0\"", 168.0, "East"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Bedroom 3 / Study", "11'0\" x 10'0\"", 110.0, "North"),
                    ("Kitchen & Utility", "10'6\" x 8'0\"", 84.0, "South-East"),
                ],
                "balconies": [
                    ("Morning Balcony", "12'6\" x 5'0\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 8.2, 14, 28, 34, "Via Tellapur-Gopanpally 100ft Road", ["Gopanpally X Road", "Wipro Junction", "ADP Boulevard"], "Direct 25-min peak commute to ADP Gachibowli"),
            ("HITEC City", 14.5, 22, 42, 48, "Via Gachibowli-Miyapur Road", ["Gachibowli Flyover", "Cyber Towers"], "Heavy rush-hour traffic between 9:00 - 10:30 AM"),
            ("Kokapet SEZ", 9.8, 12, 22, 26, "Via ORR Service Road / Kollur Exit", ["ORR Exit 2"], "Smooth continuous corridor with minimal traffic lights"),
            ("RGIA Airport", 34.0, 32, 42, 45, "Via Outer Ring Road (ORR)", ["TSPA Junction", "Shamshabad Toll"], "Express highway with signal-free transit"),
        ]
    },
    {
        "id": "PRJ-MYH-02",
        "name": "My Home Tarkshya",
        "developer": "My Home Constructions",
        "rera_id": "P02400000789",
        "micro_market": "Kokapet",
        "promoter_legal_entity": "My Home Constructions Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 4,
        "registered_handover_date": "2025-06-30",
        "handover_year": 2025,
        "status": "Ready for Handover / Fit-Outs",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 8.0,
        "clubhouse_sqft": 45000,
        "open_space_pct": 78.0,
        "units": [
            {
                "id": "TRK-T2-1801",
                "tower": "Tower 2",
                "floor": 18,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 2230,
                "carpet_area_sqft": 1585,
                "balcony_sqft": 130,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 8600,
                "floor_rise_charges": 520000,
                "corner_premium_charges": 250000,
                "rooms": [
                    ("Formal Living & Dining", "25'0\" x 15'0\"", 375.0, "East"),
                    ("Grand Master Suite", "16'0\" x 14'0\"", 224.0, "East"),
                    ("Bedroom 2", "14'0\" x 12'6\"", 175.0, "North"),
                    ("Bedroom 3", "13'0\" x 12'0\"", 156.0, "North"),
                    ("Modular Kitchen", "13'0\" x 10'0\"", 130.0, "South-East"),
                ],
                "balconies": [
                    ("Panoramic East Balcony", "15'0\" x 6'6\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 4.2, 7, 12, 15, "Via Kokapet Main Road", ["Kokapet Rotary", "GAR InfoSys", "ADP Junction"], "Fast direct commute under 15 minutes to ADP"),
            ("HITEC City", 10.5, 16, 28, 35, "Via ORR & Gachibowli Flyover", ["IIIT Junction"], "Signal-free until Gachibowli junction"),
            ("Kokapet SEZ", 1.8, 3, 5, 6, "Direct Golden Mile Corridor", ["Neopolis Boulevard"], "Immediate neighborhood access"),
            ("RGIA Airport", 28.5, 24, 30, 32, "Via ORR Exit 1", ["Rajendranagar Exit"], "Direct non-stop ORR connection"),
        ]
    },
    {
        "id": "PRJ-RJP-01",
        "name": "Rajapushpa Provincia",
        "developer": "Rajapushpa Properties",
        "rera_id": "P02400003254",
        "micro_market": "Narsingi",
        "promoter_legal_entity": "Rajapushpa Properties Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 11,
        "registered_handover_date": "2025-10-31",
        "handover_year": 2025,
        "status": "Finishing Stage",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 23.75,
        "clubhouse_sqft": 150000,
        "open_space_pct": 84.0,
        "units": [
            {
                "id": "PRV-T7-1403",
                "tower": "Tower 7 (Alba)",
                "floor": 14,
                "bhk": 3.0,
                "facing": "West",
                "is_corner_unit": 1,
                "super_built_up_sqft": 2020,
                "carpet_area_sqft": 1435,
                "balcony_sqft": 120,
                "balcony_facing": "West",
                "has_morning_sunlight": 0,
                "base_rate_per_sqft": 7400,
                "floor_rise_charges": 380000,
                "corner_premium_charges": 200000,
                "rooms": [
                    ("Living & Dining", "22'6\" x 14'0\"", 315.0, "West"),
                    ("Master Bedroom", "15'6\" x 13'0\"", 201.5, "West"),
                    ("Bedroom 2", "13'6\" x 12'0\"", 162.0, "North"),
                    ("Bedroom 3", "12'6\" x 11'6\"", 143.7, "North"),
                    ("Kitchen", "11'0\" x 9'0\"", 99.0, "South-East"),
                ],
                "balconies": [
                    ("Sunset Sky Balcony", "14'0\" x 6'0\"", "West", 0),
                ]
            },
            {
                "id": "PRV-T2-0601",
                "tower": "Tower 2 (Bonaire)",
                "floor": 6,
                "bhk": 2.0,
                "facing": "East",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1370,
                "carpet_area_sqft": 975,
                "balcony_sqft": 75,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 7400,
                "floor_rise_charges": 80000,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "18'0\" x 12'0\"", 216.0, "East"),
                    ("Master Bedroom", "13'6\" x 12'0\"", 162.0, "East"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Kitchen & Utility", "10'0\" x 8'0\"", 80.0, "South-East"),
                ],
                "balconies": [
                    ("Morning Balcony", "12'0\" x 5'0\"", "East", 1),
                ]
            },
            {
                "id": "PRV-T1-0304",
                "tower": "Tower 1 (Aura)",
                "floor": 3,
                "bhk": 2.0,
                "facing": "East",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1200,
                "carpet_area_sqft": 860,
                "balcony_sqft": 70,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6600,
                "floor_rise_charges": 0,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "18'0\" x 12'0\"", 216.0, "East"),
                    ("Master Bedroom", "13'0\" x 12'0\"", 156.0, "East"),
                    ("Bedroom 2", "11'6\" x 11'0\"", 126.5, "North"),
                    ("Kitchen & Utility", "9'6\" x 8'0\"", 76.0, "South-East"),
                ],
                "balconies": [
                    ("East Sitout Balcony", "12'0\" x 4'6\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 5.5, 9, 16, 20, "Via Narsingi-Puppalguda Main Road", ["Narsingi Rotary", "Waverock Circle", "ADP Office"], "Short 15-min rush-hour transit to ADP / Waverock"),
            ("HITEC City", 11.0, 18, 32, 38, "Via ORR & Durgam Cheruvu Cable Bridge", ["Bio-Diversity Junction"], "Scenic and rapid route via Cable Bridge"),
            ("Kokapet SEZ", 3.2, 5, 8, 10, "Via Gandipet Road", ["Ocean Park Junction"], "Quick bypass with zero red lights"),
            ("RGIA Airport", 26.0, 22, 28, 30, "Via ORR Exit 18", ["Appa Junction"], "One of the closest residential hubs to Airport via ORR"),
        ]
    },
    {
        "id": "PRJ-APR-01",
        "name": "Aparna Zenon",
        "developer": "Aparna Constructions",
        "rera_id": "P02400003719",
        "micro_market": "Financial District",
        "promoter_legal_entity": "Aparna Constructions and Estates Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 14,
        "registered_handover_date": "2027-03-31",
        "handover_year": 2027,
        "status": "Under Construction - RCC Structure Active",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 30.15,
        "clubhouse_sqft": 86000,
        "open_space_pct": 80.0,
        "units": [
            {
                "id": "ZEN-T4-2104",
                "tower": "Tower 4",
                "floor": 21,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1825,
                "carpet_area_sqft": 1295,
                "balcony_sqft": 105,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 8200,
                "floor_rise_charges": 640000,
                "corner_premium_charges": 200000,
                "rooms": [
                    ("Living & Dining", "21'0\" x 13'6\"", 283.5, "East"),
                    ("Master Bedroom", "14'6\" x 12'6\"", 181.2, "East"),
                    ("Bedroom 2", "12'6\" x 11'6\"", 143.7, "North"),
                    ("Bedroom 3", "11'6\" x 11'0\"", 126.5, "North"),
                    ("Kitchen & Dry Balcony", "11'0\" x 8'6\"", 93.5, "South-East"),
                ],
                "balconies": [
                    ("East Sun Deck", "13'6\" x 5'6\"", "East", 1),
                ]
            },
            {
                "id": "ZEN-T9-0402",
                "tower": "Tower 9",
                "floor": 4,
                "bhk": 2.0,
                "facing": "East",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1240,
                "carpet_area_sqft": 885,
                "balcony_sqft": 70,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 7200,
                "floor_rise_charges": 0,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "18'6\" x 12'0\"", 222.0, "East"),
                    ("Master Bedroom", "14'0\" x 11'6\"", 161.0, "East"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Kitchen & Utility", "10'0\" x 8'0\"", 80.0, "South-East"),
                ],
                "balconies": [
                    ("East Sunrise Balcony", "12'0\" x 5'0\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 1.2, 3, 5, 6, "Direct Nanakramguda Main Access", ["Q-City Circle", "ADP Boulevard"], "5-min short drive or cycling distance to ADP and major IT parks"),
            ("HITEC City", 8.0, 12, 22, 26, "Via Old Mumbai Highway", ["Gachibowli Circle"], "Under 25 mins in morning peak commute"),
            ("Kokapet SEZ", 4.5, 7, 10, 12, "Via Financial District Ring Road", ["Wipro Circle"], "Smooth local tech corridor link"),
            ("RGIA Airport", 30.0, 26, 32, 35, "Via ORR Nanakramguda Toll", ["Gachibowli ORR Entry"], "Direct access onto ORR without traffic lights"),
        ]
    },
    {
        "id": "PRJ-SAS-01",
        "name": "SAS Crown",
        "developer": "SAS Infra",
        "rera_id": "P02400002190",
        "micro_market": "Kokapet",
        "promoter_legal_entity": "SAS Infra Developers Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 3,
        "registered_handover_date": "2027-12-31",
        "handover_year": 2027,
        "status": "Under Construction - Super Luxury High Rise",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 4.5,
        "clubhouse_sqft": 70000,
        "open_space_pct": 75.0,
        "units": [
            {
                "id": "CRW-T1-3201",
                "tower": "Tower 1 (Imperia)",
                "floor": 32,
                "bhk": 4.5,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 4850,
                "carpet_area_sqft": 3520,
                "balcony_sqft": 380,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 10500,
                "floor_rise_charges": 1400000,
                "corner_premium_charges": 500000,
                "rooms": [
                    ("Grand Living Hall", "34'0\" x 20'0\"", 680.0, "East"),
                    ("Presidential Master Suite", "22'0\" x 16'0\"", 352.0, "East"),
                    ("Bedroom 2 (Junior Suite)", "18'0\" x 14'0\"", 252.0, "North"),
                    ("Bedroom 3", "16'0\" x 13'6\"", 216.0, "North"),
                    ("Bedroom 4", "15'0\" x 13'0\"", 195.0, "West"),
                    ("Home Cinema Lounge", "16'0\" x 12'0\"", 192.0, "West"),
                    ("Chef's Wet & Dry Kitchen", "18'0\" x 11'0\"", 198.0, "South-East"),
                ],
                "balconies": [
                    ("Wraparound Sky Deck", "30'0\" x 8'0\"", "East-North Corner", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 3.8, 6, 10, 12, "Via Kokapet Golden Mile Road", ["GAR InfoSys", "ADP Boulevard"], "Rapid corporate access to ADP"),
            ("HITEC City", 10.0, 15, 26, 32, "Via ORR Service & Gachibowli", ["Durgam Cheruvu"], "Under 30 mins even during rush hour"),
            ("Kokapet SEZ", 0.8, 2, 3, 4, "Direct Frontage Road", ["Neopolis Circle"], "Immediate walking proximity"),
            ("RGIA Airport", 27.5, 22, 28, 30, "Via ORR Kokapet Interchange", ["Shamshabad Expressway"], "Direct ORR ramp access"),
        ]
    },
    {
        "id": "PRJ-RJP-02",
        "name": "Rajapushpa Aurelia",
        "developer": "Rajapushpa Properties",
        "rera_id": "P02400006891",
        "micro_market": "Tellapur",
        "promoter_legal_entity": "Rajapushpa Properties Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 8,
        "registered_handover_date": "2028-06-30",
        "handover_year": 2028,
        "status": "Early Construction Phase",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 15.0,
        "clubhouse_sqft": 90000,
        "open_space_pct": 82.0,
        "units": [
            {
                "id": "AUR-T3-1102",
                "tower": "Tower 3",
                "floor": 11,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 2100,
                "carpet_area_sqft": 1490,
                "balcony_sqft": 125,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6800,
                "floor_rise_charges": 300000,
                "corner_premium_charges": 180000,
                "rooms": [
                    ("Living & Dining", "23'0\" x 14'0\"", 322.0, "East"),
                    ("Master Suite", "15'0\" x 13'0\"", 195.0, "East"),
                    ("Bedroom 2", "13'0\" x 12'0\"", 156.0, "North"),
                    ("Bedroom 3", "12'0\" x 11'6\"", 138.0, "North"),
                    ("Kitchen", "12'0\" x 8'6\"", 102.0, "South-East"),
                ],
                "balconies": [
                    ("Corner Morning Balcony", "14'0\" x 6'0\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 8.5, 14, 26, 32, "Via Tellapur Tech Corridor Road", ["Tellapur Junction", "ADP Boulevard"], "Expanding 6-lane road to ADP and Financial District"),
            ("HITEC City", 15.0, 24, 44, 50, "Via Gachibowli Corridor", ["Gachibowli Junction"], "Moderate morning commute"),
            ("Kokapet SEZ", 9.0, 12, 20, 24, "Via Kollur ORR Link", ["ORR Exit 2"], "Smooth outer transit ring"),
            ("RGIA Airport", 35.0, 32, 40, 45, "Via ORR Expressway", ["Airport Road"], "Full highway transit"),
        ]
    },
    {
        "id": "PRJ-CND-01",
        "name": "Candeur Lakescape",
        "developer": "Candeur Constructions",
        "rera_id": "P02400005724",
        "micro_market": "Gachibowli",
        "promoter_legal_entity": "Candeur Constructions Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 7,
        "registered_handover_date": "2028-12-31",
        "handover_year": 2028,
        "status": "Under Construction - RCC Active",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 9.1,
        "clubhouse_sqft": 80000,
        "open_space_pct": 80.0,
        "units": [
            {
                "id": "CND-T2-1104",
                "tower": "Tower 2",
                "floor": 11,
                "bhk": 2.0,
                "facing": "East",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1250,
                "carpet_area_sqft": 890,
                "balcony_sqft": 75,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6100,
                "floor_rise_charges": 180000,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "18'0\" x 12'0\"", 216.0, "East"),
                    ("Master Bedroom", "13'6\" x 12'0\"", 162.0, "East"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Kitchen & Utility", "10'0\" x 8'0\"", 80.0, "South-East"),
                ],
                "balconies": [
                    ("East Sunrise Balcony", "12'0\" x 5'0\"", "East", 1),
                ]
            },
            {
                "id": "CND-T5-1602",
                "tower": "Tower 5",
                "floor": 16,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1500,
                "carpet_area_sqft": 1065,
                "balcony_sqft": 95,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6100,
                "floor_rise_charges": 200000,
                "corner_premium_charges": 100000,
                "rooms": [
                    ("Living & Dining", "21'0\" x 13'0\"", 273.0, "East"),
                    ("Master Bedroom", "14'6\" x 12'0\"", 174.0, "East"),
                    ("Bedroom 2", "12'6\" x 11'6\"", 143.7, "North"),
                    ("Bedroom 3", "11'6\" x 11'0\"", 126.5, "North"),
                    ("Kitchen & Utility", "11'0\" x 8'6\"", 93.5, "South-East"),
                ],
                "balconies": [
                    ("East Lakeview Deck", "13'0\" x 5'6\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 6.8, 12, 20, 24, "Via Old Mumbai Highway & Gachibowli Flyover", ["Lingampally X Road", "Gachibowli Flyover", "ADP Junction"], "Fast 15-20 min direct commute to ADP Gachibowli"),
            ("HITEC City", 9.2, 16, 26, 30, "Via Gachibowli-Miyapur Road", ["IIIT Junction", "Cyber Towers"], "Signal-free transit via Gachibowli flyover"),
            ("Kokapet SEZ", 8.0, 12, 18, 22, "Via Financial District Ring Road", ["Wipro Circle"], "Smooth arterial connection"),
            ("RGIA Airport", 32.0, 28, 36, 40, "Via ORR Gachibowli Entry", ["Shamshabad Toll"], "Direct expressway route"),
        ]
    },
    {
        "id": "PRJ-HNR-01",
        "name": "Honer Signatis",
        "developer": "Honer Homes",
        "rera_id": "P02400006023",
        "micro_market": "Kollur",
        "promoter_legal_entity": "Honer Homes Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 18,
        "registered_handover_date": "2026-12-31",
        "handover_year": 2026,
        "status": "Under Construction - Structuring Active",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 27.5,
        "clubhouse_sqft": 130000,
        "open_space_pct": 81.0,
        "units": [
            {
                "id": "HNR-T7-0501",
                "tower": "Tower 7",
                "floor": 5,
                "bhk": 2.0,
                "facing": "East",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1220,
                "carpet_area_sqft": 870,
                "balcony_sqft": 70,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 5500,
                "floor_rise_charges": 0,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "18'0\" x 12'0\"", 216.0, "East"),
                    ("Master Bedroom", "13'0\" x 12'0\"", 156.0, "East"),
                    ("Bedroom 2", "11'6\" x 11'0\"", 126.5, "North"),
                    ("Kitchen & Utility", "9'6\" x 8'0\"", 76.0, "South-East"),
                ],
                "balconies": [
                    ("East Sunrise Balcony", "12'0\" x 4'6\"", "East", 1),
                ]
            },
            {
                "id": "HNR-T3-0803",
                "tower": "Tower 3",
                "floor": 8,
                "bhk": 2.5,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1450,
                "carpet_area_sqft": 1030,
                "balcony_sqft": 90,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 5600,
                "floor_rise_charges": 90000,
                "corner_premium_charges": 100000,
                "rooms": [
                    ("Living & Dining", "19'6\" x 12'6\"", 243.0, "East"),
                    ("Master Bedroom", "14'0\" x 12'0\"", 168.0, "East"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Study / Work Suite", "9'0\" x 8'0\"", 72.0, "North"),
                    ("Kitchen & Utility", "10'0\" x 8'0\"", 80.0, "South-East"),
                ],
                "balconies": [
                    ("East Corner Balcony", "12'6\" x 5'0\"", "East", 1),
                ]
            },
            {
                "id": "HNR-T4-1204",
                "tower": "Tower 4",
                "floor": 12,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1520,
                "carpet_area_sqft": 1080,
                "balcony_sqft": 95,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 5600,
                "floor_rise_charges": 150000,
                "corner_premium_charges": 100000,
                "rooms": [
                    ("Living & Dining", "21'0\" x 13'0\"", 273.0, "East"),
                    ("Master Suite", "15'0\" x 12'6\"", 187.5, "East"),
                    ("Bedroom 2", "12'6\" x 11'6\"", 143.7, "North"),
                    ("Bedroom 3", "11'6\" x 11'0\"", 126.5, "North"),
                    ("Kitchen & Utility", "11'0\" x 8'0\"", 88.0, "South-East"),
                ],
                "balconies": [
                    ("Morning Sky Balcony", "13'0\" x 5'6\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 12.0, 15, 22, 26, "Via ORR Exit 2 direct express corridor", ["Kollur Interchange", "Nanakramguda Toll", "ADP Junction"], "Fast signal-free ORR commute to ADP Gachibowli"),
            ("HITEC City", 18.0, 24, 38, 44, "Via ORR & Gachibowli Bypass", ["Gachibowli Junction"], "High-speed outer bypass"),
            ("Kokapet SEZ", 8.5, 10, 16, 18, "Via ORR Exit 1", ["Neopolis Ramp"], "Direct ORR exit"),
            ("RGIA Airport", 36.0, 30, 38, 42, "Via ORR Southbound", ["TSPA Junction"], "Straight uninterrupted expressway link"),
        ]
    },
    {
        "id": "PRJ-APR-02",
        "name": "Aparna Sarovar Zenith",
        "developer": "Aparna Constructions",
        "rera_id": "P02400000022",
        "micro_market": "Nallagandla",
        "promoter_legal_entity": "Aparna Constructions and Estates Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 13,
        "registered_handover_date": "2025-06-30",
        "handover_year": 2025,
        "status": "Ready to Move / Fit-Outs",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 24.6,
        "clubhouse_sqft": 85000,
        "open_space_pct": 80.0,
        "units": [
            {
                "id": "ASZ-T8-0604",
                "tower": "Tower 8",
                "floor": 6,
                "bhk": 2.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1200,
                "carpet_area_sqft": 855,
                "balcony_sqft": 70,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6200,
                "floor_rise_charges": 30000,
                "corner_premium_charges": 100000,
                "rooms": [
                    ("Living & Dining", "18'0\" x 12'0\"", 216.0, "East"),
                    ("Master Bedroom", "13'0\" x 12'0\"", 156.0, "East"),
                    ("Bedroom 2", "11'6\" x 11'0\"", 126.5, "North"),
                    ("Kitchen & Utility", "9'6\" x 8'0\"", 76.0, "South-East"),
                ],
                "balconies": [
                    ("East Sunrise Balcony", "12'0\" x 4'6\"", "East", 1),
                ]
            },
            {
                "id": "ASZ-T4-0902",
                "tower": "Tower 4",
                "floor": 9,
                "bhk": 2.5,
                "facing": "East",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1375,
                "carpet_area_sqft": 980,
                "balcony_sqft": 80,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6400,
                "floor_rise_charges": 120000,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "19'0\" x 12'6\"", 237.5, "East"),
                    ("Master Bedroom", "14'0\" x 12'0\"", 168.0, "East"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Study / Office", "9'0\" x 8'0\"", 72.0, "North"),
                    ("Kitchen & Utility", "10'0\" x 8'0\"", 80.0, "South-East"),
                ],
                "balconies": [
                    ("East Sunrise Balcony", "12'6\" x 5'0\"", "East", 1),
                ]
            },
            {
                "id": "ASZ-T2-1401",
                "tower": "Tower 2",
                "floor": 14,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1490,
                "carpet_area_sqft": 1060,
                "balcony_sqft": 90,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6200,
                "floor_rise_charges": 200000,
                "corner_premium_charges": 100000,
                "rooms": [
                    ("Living & Dining", "21'0\" x 13'0\"", 273.0, "East"),
                    ("Master Bedroom", "14'6\" x 12'0\"", 174.0, "East"),
                    ("Bedroom 2", "12'6\" x 11'6\"", 143.7, "North"),
                    ("Bedroom 3", "11'6\" x 11'0\"", 126.5, "North"),
                    ("Kitchen & Utility", "11'0\" x 8'0\"", 88.0, "South-East"),
                ],
                "balconies": [
                    ("Corner Morning Balcony", "13'0\" x 5'0\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District / ADP Gachibowli", 7.5, 12, 20, 24, "Via Nallagandla-Tellapur Road & Gopanpally X Road", ["Gopanpally Circle", "Wipro Junction", "ADP Boulevard"], "Easy 18-20 min drive to ADP & Financial District"),
            ("HITEC City", 11.0, 18, 30, 36, "Via HCU Road & Gachibowli", ["University X Road"], "Scenic corridor along Central University campus"),
            ("Kokapet SEZ", 9.2, 14, 22, 26, "Via Gopanpally-Kollur Link", ["ORR Exit 2"], "Direct bypass link"),
            ("RGIA Airport", 35.0, 32, 40, 45, "Via ORR Gachibowli Ramp", ["Shamshabad Toll"], "Full expressway access"),
        ]
    },
    {
        "id": "prj_sah_16751",
        "name": "Sahith Home",
        "developer": "Sahith",
        "rera_id": "P00909098668777",
        "micro_market": "Manikonda",
        "promoter_legal_entity": "Sahith Projects Ltd",
        "sanctioning_authority": "GHMC / HMDA",
        "approved_towers": 10,
        "registered_handover_date": "2027-12-31",
        "handover_year": 2027,
        "status": "Under Construction",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 20.0,
        "clubhouse_sqft": 45000,
        "open_space_pct": 50.0,
        "units": [
            {
                "id": "SAH-16751-T1-0101",
                "tower": "Tower 1",
                "floor": 1,
                "bhk": 5.0,
                "facing": "East",
                "is_corner_unit": 0,
                "super_built_up_sqft": 10000,
                "carpet_area_sqft": 6000,
                "balcony_sqft": 300,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 2000,
                "floor_rise_charges": 0,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Grand Living Pavilion", "24'0\" x 18'0\"", 432.0, "East"),
                    ("Formal Dining Lounge", "18'0\" x 14'0\"", 252.0, "North"),
                    ("Master Suite & Lounge", "20'0\" x 16'0\"", 320.0, "East"),
                    ("Guest Villa Suite", "16'0\" x 14'0\"", 224.0, "West"),
                    ("Italian Modular Kitchen", "16'0\" x 12'0\"", 192.0, "South-East"),
                ],
                "balconies": [
                    ("Private Lawn & Morning Deck", "30'0\" x 10'0\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("ADP Gachibowli", 8.2, 16, 28, 32, "Lanco Hills Road / Old Mumbai Highway", ["Lanco Hills Junction", "Khajaguda Junction"], "Moderate rush hour at Khajaguda"),
            ("HITEC City Cyber Towers", 9.5, 20, 35, 40, "Shaikpet Flyover / Durgam Cheruvu", ["Shaikpet Junction", "Mindspace Junction"], "Fast transit via Shaikpet flyover"),
            ("Financial District (Wipro Circle)", 9.0, 18, 30, 35, "Khajaguda - Nanakramguda ORR Spur", ["Khajaguda Circle", "WaveRock Junction"], "Direct ORR spur road"),
            ("RGIA Airport", 28.5, 30, 40, 42, "Neopolis ORR Exit 18", ["ORR Nanakramguda Entry", "Rajendranagar Toll"], "Direct expressway access"),
        ]
    }
]
