"""
High-fidelity seed data representing authentic, verified Hyderabad RERA residential projects.
Focuses on Kokapet, Financial District, Tellapur, Narsingi, and Gachibowli.
"""

PROJECTS_DATA = [
    {
        "id": "PRJ-MYH-01",
        "name": "My Home Akrida",
        "developer": "My Home Constructions",
        "rera_id": "P02400005128",
        "micro_market": "Tellapur",
        "promoter_legal_entity": "My Home Constructions Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 12,
        "registered_handover_date": "2026-12-31",
        "handover_year": 2026,
        "status": "Under Construction - On Schedule",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 24.5,
        "clubhouse_sqft": 100000,
        "open_space_pct": 82.5,
        "units": [
            {
                "id": "AKR-T3-1202",
                "tower": "Tower 3 (Amara)",
                "floor": 12,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1985,
                "carpet_area_sqft": 1410,
                "balcony_sqft": 115,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 7100,
                "floor_rise_charges": 360000,  # 30/sft/floor above 5th
                "corner_premium_charges": 200000,
                "rooms": [
                    ("Living & Dining", "23'0\" x 14'6\"", 333.5, "East"),
                    ("Master Bedroom", "15'0\" x 13'0\"", 195.0, "East"),
                    ("Bedroom 2", "13'0\" x 12'0\"", 156.0, "North"),
                    ("Bedroom 3 / Study", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Kitchen & Utility", "12'0\" x 9'6\"", 114.0, "South-East"),
                ],
                "balconies": [
                    ("East Corner Balcony", "14'6\" x 6'0\"", "East", 1),
                    ("Utility Sitout", "7'0\" x 4'0\"", "South", 0),
                ]
            },
            {
                "id": "AKR-T5-0804",
                "tower": "Tower 5 (Bodhi)",
                "floor": 8,
                "bhk": 2.5,
                "facing": "North",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1485,
                "carpet_area_sqft": 1055,
                "balcony_sqft": 85,
                "balcony_facing": "North",
                "has_morning_sunlight": 0,
                "base_rate_per_sqft": 7100,
                "floor_rise_charges": 120000,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "19'6\" x 12'6\"", 243.0, "North"),
                    ("Master Bedroom", "14'0\" x 12'0\"", 168.0, "North"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "West"),
                    ("Work-From-Home Study", "9'0\" x 8'0\"", 72.0, "West"),
                    ("Kitchen & Utility", "10'6\" x 8'0\"", 84.0, "South-East"),
                ],
                "balconies": [
                    ("North View Balcony", "12'6\" x 5'0\"", "North", 0),
                ]
            }
        ],
        "commutes": [
            ("Financial District", 8.2, 14, 28, 34, "Via Tellapur-Gopanpally 100ft Road", ["Gopanpally X Road", "Wipro Junction"], "Moderate evening congestion near Wipro Circle"),
            ("HITEC City", 14.5, 22, 42, 48, "Via Gachibowli-Miyapur Road", ["Gachibowli Flyover", "Cyber Towers"], "Heavy rush-hour traffic between 9:00 - 10:30 AM"),
            ("Kokapet SEZ", 9.8, 12, 22, 26, "Via ORR Service Road / Kollur Exit", ["ORR Exit 2"], "Smooth continuous corridor with minimal traffic lights"),
            ("RGIA Airport", 34.0, 32, 42, 45, "Via Outer Ring Road (ORR)", ["TSPA Junction", "Shamshabad Toll"], "Express highway with signal-free transit"),
        ]
    },
    {
        "id": "PRJ-MYH-02",
        "name": "My Home Tarkshya",
        "developer": "My Home Constructions",
        "rera_id": "P02400000789",
        "micro_market": "Kokapet",
        "promoter_legal_entity": "My Home Constructions Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 4,
        "registered_handover_date": "2025-06-30",
        "handover_year": 2025,
        "status": "Ready for Handover / Fit-Outs",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 8.0,
        "clubhouse_sqft": 45000,
        "open_space_pct": 78.0,
        "units": [
            {
                "id": "TRK-T2-1801",
                "tower": "Tower 2",
                "floor": 18,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 2230,
                "carpet_area_sqft": 1585,
                "balcony_sqft": 130,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 8600,
                "floor_rise_charges": 520000,
                "corner_premium_charges": 250000,
                "rooms": [
                    ("Formal Living & Dining", "25'0\" x 15'0\"", 375.0, "East"),
                    ("Grand Master Suite", "16'0\" x 14'0\"", 224.0, "East"),
                    ("Bedroom 2", "14'0\" x 12'6\"", 175.0, "North"),
                    ("Bedroom 3", "13'0\" x 12'0\"", 156.0, "North"),
                    ("Modular Kitchen", "13'0\" x 10'0\"", 130.0, "South-East"),
                ],
                "balconies": [
                    ("Panoramic East Balcony", "15'0\" x 6'6\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District", 4.2, 7, 12, 15, "Via Kokapet Main Road", ["Kokapet Rotary"], "Fast direct commute under 15 minutes"),
            ("HITEC City", 10.5, 16, 28, 35, "Via ORR & Gachibowli Flyover", ["IIIT Junction"], "Signal-free until Gachibowli junction"),
            ("Kokapet SEZ", 1.8, 3, 5, 6, "Direct Golden Mile Corridor", ["Neopolis Boulevard"], "Immediate neighborhood access"),
            ("RGIA Airport", 28.5, 24, 30, 32, "Via ORR Exit 1", ["Rajendranagar Exit"], "Direct non-stop ORR connection"),
        ]
    },
    {
        "id": "PRJ-RJP-01",
        "name": "Rajapushpa Provincia",
        "developer": "Rajapushpa Properties",
        "rera_id": "P02400003254",
        "micro_market": "Narsingi",
        "promoter_legal_entity": "Rajapushpa Properties Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 11,
        "registered_handover_date": "2025-10-31",
        "handover_year": 2025,
        "status": "Finishing Stage",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 23.75,
        "clubhouse_sqft": 150000,
        "open_space_pct": 84.0,
        "units": [
            {
                "id": "PRV-T7-1403",
                "tower": "Tower 7 (Alba)",
                "floor": 14,
                "bhk": 3.0,
                "facing": "West",
                "is_corner_unit": 1,
                "super_built_up_sqft": 2020,
                "carpet_area_sqft": 1435,
                "balcony_sqft": 120,
                "balcony_facing": "West",
                "has_morning_sunlight": 0,
                "base_rate_per_sqft": 7400,
                "floor_rise_charges": 380000,
                "corner_premium_charges": 200000,
                "rooms": [
                    ("Living & Dining", "22'6\" x 14'0\"", 315.0, "West"),
                    ("Master Bedroom", "15'6\" x 13'0\"", 201.5, "West"),
                    ("Bedroom 2", "13'6\" x 12'0\"", 162.0, "North"),
                    ("Bedroom 3", "12'6\" x 11'6\"", 143.7, "North"),
                    ("Kitchen", "11'0\" x 9'0\"", 99.0, "South-East"),
                ],
                "balconies": [
                    ("Sunset Sky Balcony", "14'0\" x 6'0\"", "West", 0),
                ]
            },
            {
                "id": "PRV-T2-0601",
                "tower": "Tower 2 (Bonaire)",
                "floor": 6,
                "bhk": 2.0,
                "facing": "East",
                "is_corner_unit": 0,
                "super_built_up_sqft": 1370,
                "carpet_area_sqft": 975,
                "balcony_sqft": 75,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 7400,
                "floor_rise_charges": 80000,
                "corner_premium_charges": 0,
                "rooms": [
                    ("Living & Dining", "18'0\" x 12'0\"", 216.0, "East"),
                    ("Master Bedroom", "13'6\" x 12'0\"", 162.0, "East"),
                    ("Bedroom 2", "12'0\" x 11'0\"", 132.0, "North"),
                    ("Kitchen & Utility", "10'0\" x 8'0\"", 80.0, "South-East"),
                ],
                "balconies": [
                    ("Morning Balcony", "12'0\" x 5'0\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District", 5.5, 9, 16, 20, "Via Narsingi-Puppalguda Main Road", ["Narsingi Rotary"], "Short 15-min rush-hour transit to Waverock"),
            ("HITEC City", 11.0, 18, 32, 38, "Via ORR & Durgam Cheruvu Cable Bridge", ["Bio-Diversity Junction"], "Scenic and rapid route via Cable Bridge"),
            ("Kokapet SEZ", 3.2, 5, 8, 10, "Via Gandipet Road", ["Ocean Park Junction"], "Quick bypass with zero red lights"),
            ("RGIA Airport", 26.0, 22, 28, 30, "Via ORR Exit 18", ["Appa Junction"], "One of the closest residential hubs to Airport via ORR"),
        ]
    },
    {
        "id": "PRJ-APR-01",
        "name": "Aparna Zenon",
        "developer": "Aparna Constructions",
        "rera_id": "P02400003719",
        "micro_market": "Financial District",
        "promoter_legal_entity": "Aparna Constructions and Estates Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 14,
        "registered_handover_date": "2027-03-31",
        "handover_year": 2027,
        "status": "Under Construction - RCC Structure Active",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 30.15,
        "clubhouse_sqft": 86000,
        "open_space_pct": 80.0,
        "units": [
            {
                "id": "ZEN-T4-2104",
                "tower": "Tower 4",
                "floor": 21,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 1825,
                "carpet_area_sqft": 1295,
                "balcony_sqft": 105,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 8200,
                "floor_rise_charges": 640000,
                "corner_premium_charges": 200000,
                "rooms": [
                    ("Living & Dining", "21'0\" x 13'6\"", 283.5, "East"),
                    ("Master Bedroom", "14'6\" x 12'6\"", 181.2, "East"),
                    ("Bedroom 2", "12'6\" x 11'6\"", 143.7, "North"),
                    ("Bedroom 3", "11'6\" x 11'0\"", 126.5, "North"),
                    ("Kitchen & Dry Balcony", "11'0\" x 8'6\"", 93.5, "South-East"),
                ],
                "balconies": [
                    ("East Sun Deck", "13'6\" x 5'6\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District", 1.2, 3, 5, 6, "Direct Nanakramguda Main Access", ["Q-City Circle"], "Walking/cycling distance to major IT parks"),
            ("HITEC City", 8.0, 12, 22, 26, "Via Old Mumbai Highway", ["Gachibowli Circle"], "Under 25 mins in morning peak commute"),
            ("Kokapet SEZ", 4.5, 7, 10, 12, "Via Financial District Ring Road", ["Wipro Circle"], "Smooth local tech corridor link"),
            ("RGIA Airport", 30.0, 26, 32, 35, "Via ORR Nanakramguda Toll", ["Gachibowli ORR Entry"], "Direct access onto ORR without traffic lights"),
        ]
    },
    {
        "id": "PRJ-SAS-01",
        "name": "SAS Crown",
        "developer": "SAS Infra",
        "rera_id": "P02400002190",
        "micro_market": "Kokapet",
        "promoter_legal_entity": "SAS Infra Developers Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 3,
        "registered_handover_date": "2027-12-31",
        "handover_year": 2027,
        "status": "Under Construction - Super Luxury High Rise",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 4.5,
        "clubhouse_sqft": 70000,
        "open_space_pct": 75.0,
        "units": [
            {
                "id": "CRW-T1-3201",
                "tower": "Tower 1 (Imperia)",
                "floor": 32,
                "bhk": 4.5,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 4850,
                "carpet_area_sqft": 3520,
                "balcony_sqft": 380,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 10500,
                "floor_rise_charges": 1400000,
                "corner_premium_charges": 500000,
                "rooms": [
                    ("Grand Living Hall", "34'0\" x 20'0\"", 680.0, "East"),
                    ("Presidential Master Suite", "22'0\" x 16'0\"", 352.0, "East"),
                    ("Bedroom 2 (Junior Suite)", "18'0\" x 14'0\"", 252.0, "North"),
                    ("Bedroom 3", "16'0\" x 13'6\"", 216.0, "North"),
                    ("Bedroom 4", "15'0\" x 13'0\"", 195.0, "West"),
                    ("Home Cinema Lounge", "16'0\" x 12'0\"", 192.0, "West"),
                    ("Chef's Wet & Dry Kitchen", "18'0\" x 11'0\"", 198.0, "South-East"),
                ],
                "balconies": [
                    ("Wraparound Sky Deck", "30'0\" x 8'0\"", "East-North Corner", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District", 3.8, 6, 10, 12, "Via Kokapet Golden Mile Road", ["GAR InfoSys"], "Rapid corporate access"),
            ("HITEC City", 10.0, 15, 26, 32, "Via ORR Service & Gachibowli", ["Durgam Cheruvu"], "Under 30 mins even during rush hour"),
            ("Kokapet SEZ", 0.8, 2, 3, 4, "Direct Frontage Road", ["Neopolis Circle"], "Immediate walking proximity"),
            ("RGIA Airport", 27.5, 22, 28, 30, "Via ORR Kokapet Interchange", ["Shamshabad Expressway"], "Direct ORR ramp access"),
        ]
    },
    {
        "id": "PRJ-RJP-02",
        "name": "Rajapushpa Aurelia",
        "developer": "Rajapushpa Properties",
        "rera_id": "P02400006891",
        "micro_market": "Tellapur",
        "promoter_legal_entity": "Rajapushpa Properties Pvt Ltd",
        "sanctioning_authority": "HMDA / TS-RERA",
        "approved_towers": 8,
        "registered_handover_date": "2028-06-30",
        "handover_year": 2028,
        "status": "Early Construction Phase",
        "escrow_compliant": 1,
        "litigations_reported": 0,
        "quarterly_compliance_up_to_date": 1,
        "total_acres": 15.0,
        "clubhouse_sqft": 90000,
        "open_space_pct": 82.0,
        "units": [
            {
                "id": "AUR-T3-1102",
                "tower": "Tower 3",
                "floor": 11,
                "bhk": 3.0,
                "facing": "East",
                "is_corner_unit": 1,
                "super_built_up_sqft": 2100,
                "carpet_area_sqft": 1490,
                "balcony_sqft": 125,
                "balcony_facing": "East",
                "has_morning_sunlight": 1,
                "base_rate_per_sqft": 6800,
                "floor_rise_charges": 300000,
                "corner_premium_charges": 180000,
                "rooms": [
                    ("Living & Dining", "23'0\" x 14'0\"", 322.0, "East"),
                    ("Master Suite", "15'0\" x 13'0\"", 195.0, "East"),
                    ("Bedroom 2", "13'0\" x 12'0\"", 156.0, "North"),
                    ("Bedroom 3", "12'0\" x 11'6\"", 138.0, "North"),
                    ("Kitchen", "12'0\" x 8'6\"", 102.0, "South-East"),
                ],
                "balconies": [
                    ("Corner Morning Balcony", "14'0\" x 6'0\"", "East", 1),
                ]
            }
        ],
        "commutes": [
            ("Financial District", 8.5, 14, 26, 32, "Via Tellapur Tech Corridor Road", ["Tellapur Junction"], "Expanding 6-lane road under development"),
            ("HITEC City", 15.0, 24, 44, 50, "Via Gachibowli Corridor", ["Gachibowli Junction"], "Moderate morning commute"),
            ("Kokapet SEZ", 9.0, 12, 20, 24, "Via Kollur ORR Link", ["ORR Exit 2"], "Smooth outer transit ring"),
            ("RGIA Airport", 35.0, 32, 40, 45, "Via ORR Expressway", ["Airport Road"], "Full highway transit"),
        ]
    }
]
